<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>25ffe3a5-8af3-468f-83df-5212377d69de</elementGuidId>
    <imagePath></imagePath>
    <name>kendo_ChipOption</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/kendo-drawer-container[1]/kendo-drawer-content[1]/app-pet-v1-component[1]/div[1]/div[1]/div[1]/kendo-chiplist[1]/kendo-chip[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="k-chip\ k-chip-md\ k-rounded-md\ k-chip-solid-base\ k-chip-solid\ k-focus"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=option[name="Chip 2"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>