<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2a3caee6-b678-4d13-96e6-0d4e734cba81</elementGuidId>
    <imagePath></imagePath>
    <name>kendo_DrawerContainer</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/kendo-drawer-container[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="k-drawer-container\ k-drawer-push\ k-drawer-mini"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>kendo-drawer-container</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>