<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e40ba128-25a2-4039-a2bb-0865f5ca8c7c</elementGuidId>
    <imagePath></imagePath>
    <name>input_TaskName</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/kendo-drawer-container[1]/kendo-drawer-content[1]/app-pet-v1-component[1]/kendo-dialog[1]/div[2]/div[1]/form[1]/kendo-formfield[1]/div[1]/kendo-textbox[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#k-c775ded5-3c5d-41b1-8928-67bd655ea7fd</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'k-c775ded5-3c5d-41b1-8928-67bd655ea7fd') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=textbox[name="Task Name"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>k-c775ded5-3c5d-41b1-8928-67bd655ea7fd</value>
        <webElementGuid>a98c8c66-1b8c-41c4-8ba2-b61ea11c2abc</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>a98c8c66-1b8c-41c4-8ba2-b61ea11c2abc</webElementGuid>
    </webElementProperties>
</WebElementEntity>