<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>61cc9752-cdc5-4e6b-8d17-a9994586248a</elementGuidId>
    <imagePath></imagePath>
    <name>input_CreateTask</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/kendo-drawer-container[1]/kendo-drawer-content[1]/app-pet-v1-component[1]/kendo-dialog[1]/div[2]/div[1]/form[1]/kendo-formfield[1]/div[1]/kendo-textbox[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#k-cfaa74c8-2584-423f-a65f-ff4c66e7b1a3</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'k-cfaa74c8-2584-423f-a65f-ff4c66e7b1a3') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=textbox[name="Task Name"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>k-cfaa74c8-2584-423f-a65f-ff4c66e7b1a3</value>
        <webElementGuid>72549dc4-1197-405f-bb5d-f46f8b3e282e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>72549dc4-1197-405f-bb5d-f46f8b3e282e</webElementGuid>
    </webElementProperties>
</WebElementEntity>