<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e064afa9-83ac-4996-b6f2-fa1b30ac1382</elementGuidId>
    <imagePath></imagePath>
    <name>input_SearchTasks</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/kendo-drawer-container[1]/kendo-drawer-content[1]/app-pet-v1-component[1]/div[1]/div[1]/div[1]/div[1]/kendo-textbox[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#k-63e0d6fc-7e1d-4c75-ba42-f8513bc09c83</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'k-63e0d6fc-7e1d-4c75-ba42-f8513bc09c83') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=textbox[name="Search tasks"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>k-63e0d6fc-7e1d-4c75-ba42-f8513bc09c83</value>
        <webElementGuid>a98c8c66-1b8c-41c4-8ba2-b61ea11c2abc</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>a98c8c66-1b8c-41c4-8ba2-b61ea11c2abc</webElementGuid>
    </webElementProperties>
</WebElementEntity>