<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f74ed9f5-a228-4de2-8acc-f6ec3dc02fde</elementGuidId>
    <imagePath></imagePath>
    <name>textarea_Description2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/kendo-drawer-container[1]/kendo-drawer-content[1]/app-pet-v1-component[1]/kendo-dialog[1]/div[2]/div[1]/form[1]/kendo-formfield[2]/div[1]/textarea[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-valid\ k-textarea\ k-input\ k-input-md\ k-rounded-md\ k-input-solid\ k-autofill\ ng-dirty\ ng-touched"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[placeholder="Description"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>