<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0ed42545-9b62-4fa4-b5e5-cb35a76bda46</elementGuidId>
    <imagePath></imagePath>
    <name>input_LastName</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/kendo-drawer-container[1]/kendo-drawer-content[1]/app-profile-component[1]/div[1]/div[1]/div[1]/form[1]/fieldset[1]/kendo-formfield[3]/div[1]/kendo-textbox[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#k-36650916-e379-4ca6-8eb9-f5aa27202b6d</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'k-{{phone}}-e379-4ca6-8eb9-f5aa27202b6d') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Last Name"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>k-{{phone}}-e379-4ca6-8eb9-f5aa27202b6d</value>
        <webElementGuid>72549dc4-1197-405f-bb5d-f46f8b3e282e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>72549dc4-1197-405f-bb5d-f46f8b3e282e</webElementGuid>
    </webElementProperties>
</WebElementEntity>