<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5d78e28b-eb10-4147-a436-e31469210b42</elementGuidId>
    <imagePath></imagePath>
    <name>input_EmailAddress</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/kendo-drawer-container[1]/kendo-drawer-content[1]/app-profile-component[1]/div[1]/div[1]/div[1]/form[1]/fieldset[1]/kendo-formfield[4]/div[1]/kendo-textbox[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#k-2f305451-e23c-45e0-8c81-5318ab08eba3</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'{{name}}-2f305451-e23c-45e0-8c81-5318ab08eba3') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Email Address"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>{{name}}-2f305451-e23c-45e0-8c81-5318ab08eba3</value>
        <webElementGuid>72549dc4-1197-405f-bb5d-f46f8b3e282e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>72549dc4-1197-405f-bb5d-f46f8b3e282e</webElementGuid>
    </webElementProperties>
</WebElementEntity>