<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>58e85f72-8f13-4a70-a0d8-f2140877a35d</elementGuidId>
    <imagePath></imagePath>
    <name>input_FirstName</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/kendo-drawer-container[1]/kendo-drawer-content[1]/app-profile-component[1]/div[1]/div[1]/div[1]/form[1]/fieldset[1]/kendo-formfield[2]/div[1]/kendo-textbox[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#k-bed460d7-2b8c-43f1-9560-0ae5b44e46e8</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'k-bed460d7-2b8c-43f1-9560-0ae5b44e46e8') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="First Name"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>k-bed460d7-2b8c-43f1-9560-0ae5b44e46e8</value>
        <webElementGuid>72549dc4-1197-405f-bb5d-f46f8b3e282e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>72549dc4-1197-405f-bb5d-f46f8b3e282e</webElementGuid>
    </webElementProperties>
</WebElementEntity>