<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ae310712-9aca-45fb-a36c-f2f956cc02cc</elementGuidId>
    <imagePath></imagePath>
    <name>item_Team2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/kendo-drawer-container[1]/kendo-drawer[1]/div[1]/ul[1]/li[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[role="menuitem"]:nth-child(1)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Team"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>