<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0ae149b8-0cbe-4764-830d-77a05083fa43</elementGuidId>
    <imagePath></imagePath>
    <name>label_OrganicTeam</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/kendo-drawer-container[1]/kendo-drawer-content[1]/app-profile-component[1]/div[1]/div[1]/div[1]/form[1]/fieldset[1]/kendo-formfield[9]/div[1]/ul[1]/li[3]/kendo-label[1]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[for="k-531b2fa3-3096-4477-b871-17ede4c1a0bb"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text="Organic Team"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>