<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c0a96693-bdb9-4873-a52e-4e40136f315d</elementGuidId>
    <imagePath></imagePath>
    <name>span_ClearButton</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/kendo-drawer-container[1]/kendo-drawer-content[1]/app-profile-component[1]/div[1]/div[1]/div[1]/form[1]/fieldset[1]/kendo-formfield[2]/div[1]/kendo-textbox[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="k-form-field"]:nth-child(2) [role="button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Clear')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>kendo-formfield &gt;&gt; internal:has-text="First Name"i &gt;&gt; internal:label="Clear"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Clear</value>
        <webElementGuid>72549dc4-1197-405f-bb5d-f46f8b3e282e</webElementGuid>
    </webElementProperties>
</WebElementEntity>