<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d6adadfd-b47e-4fc5-99d2-a094e3c2dce4</elementGuidId>
    <imagePath></imagePath>
    <name>input_TaskName</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/kendo-drawer-container[1]/kendo-drawer-content[1]/app-pet-v1-component[1]/div[1]/div[1]/div[1]/kendo-formfield[1]/div[1]/kendo-textbox[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#k-6e81085c-c680-4cd2-832f-a55305a62e81</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'k-6e81085c-c680-4cd2-832f-a55305a62e81') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=textbox[name="Task Name"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>k-6e81085c-c680-4cd2-832f-a55305a62e81</value>
        <webElementGuid>955e2b1e-3a81-45e7-bcf3-53fcaecc8d83</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>955e2b1e-3a81-45e7-bcf3-53fcaecc8d83</webElementGuid>
    </webElementProperties>
</WebElementEntity>