<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>de52813c-c0ce-475f-8ec7-a0b515cb6e0f</elementGuidId>
    <imagePath></imagePath>
    <name>input_TaskName2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/kendo-drawer-container[1]/kendo-drawer-content[1]/app-pet-v1-component[1]/div[1]/div[1]/div[1]/kendo-formfield[1]/div[1]/kendo-textbox[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#k-720d6c6e-8ed2-452a-bfda-d2019e661d7f</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'k-720d6c6e-8ed2-452a-bfda-{{mac_address}}') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=textbox[name="Task Name"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>k-720d6c6e-8ed2-452a-bfda-{{mac_address}}</value>
        <webElementGuid>a98c8c66-1b8c-41c4-8ba2-b61ea11c2abc</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>a98c8c66-1b8c-41c4-8ba2-b61ea11c2abc</webElementGuid>
    </webElementProperties>
</WebElementEntity>